const depts = [
  {
    icon: '🏷️', name: 'Branding',
    desc: 'Xây dựng nhận diện, cảm xúc và giá trị thương hiệu — nền tảng của mọi hoạt động marketing.',
    color: 'rgba(249,115,22,0.06)', border: 'rgba(249,115,22,0.2)', ai: 45,
    roles:   ['Brand Executive', 'Brand Manager', 'Creative Planner', 'Communication Executive', 'Brand Strategist'],
    skills:  ['Brand Strategy', 'Consumer Insight', 'Storytelling', 'Market Research', 'Visual Identity', 'Brand Guideline'],
    tools:   ['Figma', 'Illustrator', 'Photoshop', 'Notion', 'Canva'],
    aiUses:  ['AI brainstorm campaign', 'AI viết brand concept', 'AI tạo moodboard', 'AI phân tích insight', 'AI generate logo idea', 'AI competitor analysis'],
  },
  {
    icon: '⚡', name: 'Performance',
    desc: 'Tối ưu quảng cáo trả phí đa kênh — Facebook Ads, Google Ads, TikTok Ads để đạt ROAS cao nhất.',
    color: 'rgba(52,211,153,0.06)', border: 'rgba(52,211,153,0.2)', ai: 82,
    roles:   ['Performance Marketer', 'Media Buyer', 'Ads Specialist', 'Growth Hacker', 'PPC Manager'],
    skills:  ['Facebook Ads', 'Google Ads', 'TikTok Ads', 'A/B Testing', 'Conversion Optimization', 'ROAS / CPA'],
    tools:   ['Meta Ads Manager', 'Google Ads', 'TikTok Ads Manager', 'Google Tag Manager', 'Data Studio'],
    aiUses:  ['AI tối ưu bidding tự động', 'AI generate ad creative', 'AI phân tích audience', 'AI dự đoán ROAS', 'AI viết ad copy', 'Meta Advantage+'],
  },
  {
    icon: '✍️', name: 'Content',
    desc: 'Xây dựng chiến lược nội dung, sản xuất content đa nền tảng và tối ưu engagement.',
    color: 'rgba(230,48,34,0.06)', border: 'rgba(230,48,34,0.18)', ai: 88,
    roles:   ['Content Strategist', 'Copywriter', 'Content Creator', 'Social Content', 'Editorial Manager'],
    skills:  ['Copywriting', 'Content Calendar', 'Storytelling', 'SEO Writing', 'Hook Writing', 'Brand Voice'],
    tools:   ['Notion', 'WordPress', 'Canva', 'ChatGPT', 'Hemingway'],
    aiUses:  ['AI viết bài tự động', 'AI tối ưu headline', 'AI lên content calendar', 'AI phân tích engagement', 'AI repurpose content', 'AI viết caption MXH'],
  },
  {
    icon: '📱', name: 'Social Media',
    desc: 'Quản trị fanpage, xây dựng cộng đồng và tối ưu organic reach trên các nền tảng MXH.',
    color: 'rgba(167,139,250,0.06)', border: 'rgba(167,139,250,0.2)', ai: 60,
    roles:   ['Social Media Manager', 'Community Manager', 'Social Strategist', 'Influencer Manager', 'Page Admin'],
    skills:  ['Facebook Management', 'TikTok Strategy', 'Community Building', 'Influencer Marketing', 'Viral Content', 'Live Selling'],
    tools:   ['Meta Business Suite', 'Buffer', 'Hootsuite', 'TikTok Studio', 'Sprout Social'],
    aiUses:  ['AI lên lịch đăng bài', 'AI phân tích hashtag', 'AI gợi ý trend', 'AI tạo caption nhanh', 'AI báo cáo tự động'],
  },
  {
    icon: '🔍', name: 'SEO / GEO',
    desc: 'Tối ưu công cụ tìm kiếm truyền thống và AI — từ technical SEO đến GEO (Generative Engine Optimization).',
    color: 'rgba(96,165,250,0.06)', border: 'rgba(96,165,250,0.2)', ai: 72,
    roles:   ['SEO Specialist', 'SEO Manager', 'Technical SEO', 'Content SEO', 'GEO Strategist'],
    skills:  ['On-page SEO', 'Technical SEO', 'Link Building', 'Keyword Research', 'GEO / AI Search', 'Core Web Vitals'],
    tools:   ['Ahrefs', 'SEMrush', 'Google Search Console', 'Screaming Frog', 'SurferSEO'],
    aiUses:  ['AI viết meta description', 'AI cluster từ khóa', 'AI tối ưu schema', 'AI phân tích backlink', 'AI cho AI Overview citation', 'AI content brief'],
  },
  {
    icon: '🎨', name: 'Design',
    desc: 'Thiết kế ấn phẩm truyền thông, visual identity và UI/UX cho các kênh digital và print.',
    color: 'rgba(244,114,182,0.06)', border: 'rgba(244,114,182,0.2)', ai: 70,
    roles:   ['Graphic Designer', 'Visual Designer', 'UI/UX Designer', 'Art Director', 'Motion Designer'],
    skills:  ['Visual Design', 'Typography', 'Color Theory', 'UI/UX', 'Motion Graphics', 'Brand Collateral'],
    tools:   ['Photoshop', 'Illustrator', 'Figma', 'After Effects', 'Canva', 'Midjourney'],
    aiUses:  ['AI generate hình ảnh', 'AI xóa phông tự động', 'AI tạo mockup', 'AI upscale ảnh', 'AI tạo animation', 'Canva AI magic design'],
  },
  {
    icon: '🎬', name: 'Video',
    desc: 'Sản xuất video quảng cáo, short-form content cho TikTok, Reels và YouTube.',
    color: 'rgba(251,191,36,0.06)', border: 'rgba(251,191,36,0.2)', ai: 78,
    roles:   ['Video Producer', 'Video Editor', 'Motion Designer', 'Content Videographer', 'TikToker'],
    skills:  ['Video Editing', 'Color Grading', 'Script Writing', 'Short-form Video', 'Motion Graphics', 'Hook Strategy'],
    tools:   ['Premiere Pro', 'After Effects', 'DaVinci Resolve', 'CapCut', 'TikTok Studio'],
    aiUses:  ['AI generate video (Kling/Sora)', 'AI dựng tự động', 'AI viết script', 'AI tạo voice-over', 'AI auto subtitle', 'AI color grade'],
  },
  {
    icon: '🔗', name: 'CRM & Auto',
    desc: 'Tự động hoá marketing, quản lý khách hàng và xây dựng hệ thống nurturing hiệu quả.',
    color: 'rgba(34,211,238,0.06)', border: 'rgba(34,211,238,0.2)', ai: 80,
    roles:   ['CRM Manager', 'Marketing Automation', 'Email Marketer', 'Customer Success', 'RevOps'],
    skills:  ['Email Marketing', 'Marketing Automation', 'CRM Management', 'Lead Nurturing', 'Segmentation', 'A/B Testing'],
    tools:   ['HubSpot', 'Mailchimp', 'ActiveCampaign', 'Klaviyo', 'Zapier'],
    aiUses:  ['AI cá nhân hoá email', 'AI phân đoạn khách hàng', 'AI dự đoán churn', 'AI gợi ý upsell', 'AI chatbot CSKH', 'AI tối ưu send time'],
  },
  {
    icon: '📊', name: 'Analytics',
    desc: 'Đo lường hiệu quả marketing, phân tích dữ liệu và đưa ra quyết định dựa trên data.',
    color: 'rgba(16,185,129,0.06)', border: 'rgba(16,185,129,0.2)', ai: 85,
    roles:   ['Marketing Analyst', 'Data Analyst', 'BI Analyst', 'Growth Analyst', 'Performance Analyst'],
    skills:  ['Google Analytics', 'Data Visualization', 'Attribution Modeling', 'Cohort Analysis', 'SQL Cơ bản', 'Dashboard'],
    tools:   ['GA4', 'Looker Studio', 'Meta Pixel', 'Mixpanel', 'Google Sheets'],
    aiUses:  ['AI phân tích báo cáo', 'AI dự đoán xu hướng', 'AI tạo dashboard tự động', 'AI anomaly detection', 'AI insight từ data', 'AI viết báo cáo'],
  },
  {
    icon: '🤖', name: 'AI Marketing',
    desc: 'Ứng dụng AI vào toàn bộ quy trình Marketing — từ research, sáng tạo đến tối ưu và đo lường.',
    color: 'rgba(230,48,34,0.06)', border: 'rgba(230,48,34,0.18)', ai: 98,
    roles:   ['AI Marketing Specialist', 'Prompt Engineer', 'AI Content Lead', 'AI Ads Manager', 'Marketing Technologist'],
    skills:  ['Prompt Engineering', 'AI Workflow Design', 'LLM Integration', 'AI Tool Evaluation', 'Automation', 'AI Ethics'],
    tools:   ['ChatGPT', 'Claude', 'Midjourney', 'Kling AI', 'Make.com', 'Zapier AI'],
    aiUses:  ['AI làm tất cả mọi thứ 😄', 'Prompt marketing chuyên sâu', 'AI workflow end-to-end', 'Multi-agent automation', 'AI brand voice training', 'AI performance loop'],
  },
];

module.exports = depts;